### ISSUE TITLE
[Error] cannot open shared object file

### ISSUE THREAD

**Issue by jakobjung10** [pmdtechnologies/SampleYOLO#4]
**Error:**
```
File "/home/madas/Documents/pmd/flexx2/libroyale-5.10.0.2751-LINUX-x86-64Bit/python/roypy.py", line 15, in <module>
  import _roypy
ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
madas@madas-Jupi
```

**Specifications:**
OS: Linux Ubuntu 22.04 (x86-64)
Royale-version: libroyale-5.10.0.2751-LINUX-x86-64Bit
python-version: 3.10.12

I also set ROYALE_DIR in the python-script:
`ROYALE_DIR = "/home/madas/Documents/pmd/flexx2/libroyale-5.10.0.2751-LINUX-x86-64Bit/python"`

**Comment by pmdStrauch** [comment]
Hi, 
there is an error in the tutorial. Instead of pointing out a fixed Python version that should be used it should refer to the README in the python folder of the Royale package. There you can look up the Python version needed for this Royale version and platform. In case of Royale 5.10 and Linux x86 64Bit it should be Python 3.8.
